name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21'

    - name: Build for Linux
      run: GOOS=linux GOARCH=amd64 go build -o social-profile-linux-amd64 main.go

    - name: Build for Windows
      run: GOOS=windows GOARCH=amd64 go build -o social-profile-windows-amd64.exe main.go

    - name: Build for MacOS
      run: GOOS=darwin GOARCH=amd64 go build -o social-profile-darwin-amd64 main.go

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Git
      run: git config --global user.email "action@github.com" && git config --global user.name "GitHub Action"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: v1.0.0
        release_name: Release v1.0.0
        draft: false
        prerelease: false

    - name: Upload Linux Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: social-profile-linux-amd64
        asset_name: social-profile-linux-amd64
        asset_content_type: application/octet-stream

    - name: Upload Windows Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: social-profile-windows-amd64.exe
        asset_name: social-profile-windows-amd64.exe
        asset_content_type: application/octet-stream

    - name: Upload MacOS Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: social-profile-darwin-amd64
        asset_name: social-profile-darwin-amd64
        asset_content_type: application/octet-stream

