name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    env:
      GOROOT: /opt/hostedtoolcache/go/1.21.9/x64
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'

      - name: Build for Linux, Windows, and MacOS
        run: |
          GOOS=linux GOARCH=amd64 go build -o social-profile-linux-amd64 main.go
          GOOS=windows GOARCH=amd64 go build -o social-profile-windows-amd64.exe main.go
          GOOS=darwin GOARCH=amd64 go build -o social-profile-darwin-amd64 main.go

      - name: Set up Git
        run: git config --global user.email "action@github.com" && git config --global user.name "GitHub Action"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: v1.0.0
          release_name: Release v1.0.0
          draft: false
          prerelease: false

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: social-profile-linux-amd64 social-profile-windows-amd64.exe social-profile-darwin-amd64
          asset_name: social-profile-linux-amd64 social-profile-windows-amd64.exe social-profile-darwin-amd64
          asset_content_type: application/octet-stream application/octet-stream application/octet-stream
