# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build Linux
      run: GOOS=linux GOARCH=amd64 go build -o social-profile-linux-amd64 main.go 
    - name: Build Windows
      run: GOOS=windows GOARCH=amd64 go build -o social-profile-windows-amd64.exe main.go

    - name: Build macOS
      run: GOOS=darwin GOARCH=amd64 go build -o social-profile-darwin-amd64 main.go 

    - name: Test
      run: go test -v ./...
